spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/bookmyshow
spring.datasource.username=root
spring.datasource.password=projuser@1234
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
driverClassName=com.mysql.cj.jdbc.Driver

